#!/bin/bash
# strip-external-services.sh
# Automated script to remove external service dependencies from Vibe Kanban
# Usage: ./scripts/strip-external-services.sh [minimal|pragmatic|paranoid]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_ROOT"

STRATEGY="${1:-pragmatic}"

echo "🔒 Vibe Kanban External Services Removal Script"
echo "Strategy: $STRATEGY"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_success() {
    echo -e "${GREEN}✓${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}⚠${NC}  $1"
}

log_error() {
    echo -e "${RED}✗${NC} $1"
}

backup_file() {
    local file="$1"
    if [ -f "$file" ]; then
        cp "$file" "$file.backup"
        log_success "Backed up: $file"
    fi
}

# Create backup directory
BACKUP_DIR="$PROJECT_ROOT/.external-services-backup-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$BACKUP_DIR"
log_success "Created backup directory: $BACKUP_DIR"

# ============================================================================
# PRIORITY 1: Critical - Remove Sentry & PostHog
# ============================================================================

echo ""
echo "📋 Phase 1: Removing Critical Tracking Services"
echo "-------------------------------------------"

# Frontend: Comment out Sentry in main.tsx
if [ -f "frontend/src/main.tsx" ]; then
    backup_file "frontend/src/main.tsx"
    
    # Use perl for more reliable multiline replacements
    perl -i -pe 's/^(import \* as Sentry from.*$)/\/\/ REMOVED: $1/g' frontend/src/main.tsx
    perl -i -pe 's/^(import posthog from.*$)/\/\/ REMOVED: $1/g' frontend/src/main.tsx
    perl -i -pe 's/^(import \{ PostHogProvider \}.*$)/\/\/ REMOVED: $1/g' frontend/src/main.tsx
    
    # Comment out Sentry.init block
    sed -i.bak '/^Sentry\.init/,/^Sentry\.setTag/s/^/\/\/ REMOVED: /' frontend/src/main.tsx
    
    # Comment out PostHog init block
    sed -i.bak '/^if (/,/^}/s/^posthog/\/\/ REMOVED: posthog/' frontend/src/main.tsx
    
    log_success "Disabled Sentry & PostHog in frontend/src/main.tsx"
else
    log_error "frontend/src/main.tsx not found"
fi

# Frontend: Update App.tsx
if [ -f "frontend/src/App.tsx" ]; then
    backup_file "frontend/src/App.tsx"
    
    sed -i.bak 's/^import { usePostHog }/\/\/ REMOVED: import { usePostHog }/' frontend/src/App.tsx
    sed -i.bak 's/const posthog = usePostHog();/\/\/ REMOVED: const posthog = usePostHog();/' frontend/src/App.tsx
    
    log_success "Disabled PostHog in frontend/src/App.tsx"
fi

# Backend: Disable Sentry
if [ -f "crates/server/src/main.rs" ]; then
    backup_file "crates/server/src/main.rs"
    
    sed -i.bak 's/utils::sentry::init_once/\/\/ REMOVED: utils::sentry::init_once/' crates/server/src/main.rs
    
    log_success "Disabled Sentry in crates/server/src/main.rs"
fi

if [ -f "crates/server/src/bin/mcp_task_server.rs" ]; then
    backup_file "crates/server/src/bin/mcp_task_server.rs"
    
    sed -i.bak 's/utils::sentry::init_once/\/\/ REMOVED: utils::sentry::init_once/' crates/server/src/bin/mcp_task_server.rs
    
    log_success "Disabled Sentry in MCP task server"
fi

# Disable Remote API
cat > .env.local << 'EOF'
# Local-only configuration
# Generated by strip-external-services.sh

# Disable remote features
VK_SHARED_API_BASE=
VITE_VK_SHARED_API_BASE=

# Disable analytics
POSTHOG_API_KEY=
POSTHOG_API_ENDPOINT=
VITE_POSTHOG_API_KEY=
VITE_POSTHOG_API_ENDPOINT=

# Local ports
FRONTEND_PORT=3000
BACKEND_PORT=3001
HOST=127.0.0.1
EOF

log_success "Created .env.local with remote features disabled"

# ============================================================================
# PRIORITY 2: Important - Remove Social Widgets (if pragmatic or paranoid)
# ============================================================================

if [ "$STRATEGY" = "pragmatic" ] || [ "$STRATEGY" = "paranoid" ]; then
    echo ""
    echo "📋 Phase 2: Removing Social Widgets"
    echo "-----------------------------------"
    
    # Remove Discord widget
    if [ -f "frontend/src/hooks/useDiscordOnlineCount.ts" ]; then
        cp "frontend/src/hooks/useDiscordOnlineCount.ts" "$BACKUP_DIR/"
        cat > frontend/src/hooks/useDiscordOnlineCount.ts << 'EOF'
// REMOVED: Discord online count widget
// This file was automatically disabled by strip-external-services.sh

export function useDiscordOnlineCount() {
  return { data: null, isLoading: false, error: null };
}
EOF
        log_success "Disabled Discord widget"
    fi
    
    # Remove GitHub stars widget
    if [ -f "frontend/src/hooks/useGitHubStars.ts" ]; then
        cp "frontend/src/hooks/useGitHubStars.ts" "$BACKUP_DIR/"
        cat > frontend/src/hooks/useGitHubStars.ts << 'EOF'
// REMOVED: GitHub stars widget
// This file was automatically disabled by strip-external-services.sh

export function useGitHubStars() {
  return { data: null, isLoading: false, error: null };
}
EOF
        log_success "Disabled GitHub stars widget"
    fi
fi

# ============================================================================
# PRIORITY 3: Optional - Update Branding (if paranoid)
# ============================================================================

if [ "$STRATEGY" = "paranoid" ]; then
    echo ""
    echo "📋 Phase 3: Updating Branding & Links"
    echo "-------------------------------------"
    
    # Update git default email
    if [ -f "crates/git/src/lib.rs" ]; then
        backup_file "crates/git/src/lib.rs"
        
        sed -i.bak 's/noreply@vibekanban\.com/noreply@localhost/g' crates/git/src/lib.rs
        
        log_success "Updated git default email"
    fi
    
    # Remove PR branding
    if [ -f "shared/types.ts" ]; then
        backup_file "shared/types.ts"
        
        sed -i.bak 's|This PR was written using \[Vibe Kanban\](https://vibekanban.com)|This PR was created automatically|g' shared/types.ts
        
        log_success "Updated PR description template"
    fi
    
    # Update release notes URL
    if [ -f "frontend/src/components/dialogs/global/ReleaseNotesDialog.tsx" ]; then
        backup_file "frontend/src/components/dialogs/global/ReleaseNotesDialog.tsx"
        
        sed -i.bak "s|https://vibekanban.com/release-notes|/release-notes.md|g" frontend/src/components/dialogs/global/ReleaseNotesDialog.tsx
        
        log_success "Updated release notes URL to local file"
    fi
fi

# ============================================================================
# PRIORITY 4: Remove Remote Crate (if paranoid)
# ============================================================================

if [ "$STRATEGY" = "paranoid" ]; then
    echo ""
    echo "📋 Phase 4: Removing Remote Features"
    echo "------------------------------------"
    
    if [ -f "Cargo.toml" ]; then
        backup_file "Cargo.toml"
        
        # Move remote to exclude list
        sed -i.bak '/^members = \[/,/^\]/{
            /crates\/remote/d
            /crates\/review/d
            /crates\/deployment/d
        }' Cargo.toml
        
        # Add to exclude if not present
        if ! grep -q "^exclude = " Cargo.toml; then
            sed -i.bak '/^members = \[/,/^\]/a\
exclude = ["crates/remote", "crates/review", "crates/deployment"]
' Cargo.toml
        fi
        
        log_success "Excluded remote crates from workspace"
    fi
    
    log_warning "Note: Remote crates not deleted, just excluded from build"
    log_warning "To delete: rm -rf crates/remote crates/review remote-frontend"
fi

# ============================================================================
# Cleanup
# ============================================================================

echo ""
echo "📋 Cleanup"
echo "---------"

# Remove .bak files created by sed
find . -name "*.bak" -type f -delete 2>/dev/null || true
log_success "Removed temporary .bak files"

# ============================================================================
# Summary
# ============================================================================

echo ""
echo "========================================"
echo "✅ External Services Removal Complete"
echo "========================================"
echo ""
echo "Strategy: $STRATEGY"
echo "Backup location: $BACKUP_DIR"
echo ""
echo "What was removed/disabled:"
case $STRATEGY in
    minimal)
        echo "  - ✅ Sentry error tracking"
        echo "  - ✅ PostHog analytics"
        echo "  - ✅ Remote API disabled via .env"
        ;;
    pragmatic)
        echo "  - ✅ Sentry error tracking"
        echo "  - ✅ PostHog analytics"
        echo "  - ✅ Remote API disabled via .env"
        echo "  - ✅ Discord online count widget"
        echo "  - ✅ GitHub stars widget"
        ;;
    paranoid)
        echo "  - ✅ Sentry error tracking"
        echo "  - ✅ PostHog analytics"
        echo "  - ✅ Remote API disabled via .env"
        echo "  - ✅ Discord online count widget"
        echo "  - ✅ GitHub stars widget"
        echo "  - ✅ Git default email updated"
        echo "  - ✅ PR branding removed"
        echo "  - ✅ Release notes URL localized"
        echo "  - ✅ Remote crates excluded"
        ;;
esac
echo ""
echo "Next steps:"
echo "  1. Review the changes in modified files"
echo "  2. Test the application: pnpm run dev"
echo "  3. Run offline test (disconnect internet)"
echo "  4. If satisfied, remove backup: rm -rf $BACKUP_DIR"
echo ""
echo "To revert changes, restore from: $BACKUP_DIR"
echo ""
echo "For manual dependency cleanup, run:"
echo "  cd frontend && pnpm remove @sentry/react @sentry/vite-plugin posthog-js"
echo "  # Then edit Cargo.toml files to remove sentry and sentry-tracing"
echo ""

# Test if app still builds
echo "Testing build..."
if pnpm run check > /dev/null 2>&1; then
    log_success "Frontend type check passed"
else
    log_warning "Frontend type check failed - review changes"
fi

if cargo check --workspace > /dev/null 2>&1; then
    log_success "Backend build check passed"
else
    log_warning "Backend build check failed - review changes"
fi

echo ""
log_success "Script completed successfully!"
